from common.exceptions.exceptions import KnownException


class DockerNotAvailableException(KnownException):
    pass
